# -*- coding: utf-8 -*-
"""keras_ocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmmJQn20g57jiAFm13-O_riDJwRKWHFM
"""

# installation
!pip install keras-ocr -q

import keras_ocr

pipeline = keras_ocr.pipeline.Pipeline()
extract_info = pipeline.recognize(['4.jpg'])
print(extract_info[0][0])

import pandas as pd
diz_cols = {'word':[],'box':[]}
for el in extract_info[0]:
    diz_cols['word'].append(el[0])
    diz_cols['box'].append(el[1])
kerasocr_res = pd.DataFrame.from_dict(diz_cols)
print(kerasocr_res['word'])

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(kerasocr_res['word'])