# -*- coding: utf-8 -*-
"""paddle_OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wAFOi8XSKfL9nzFY1dkAf_xQkn6dsKyc
"""

!pip install paddleocr

!pip install paddlepaddle

!pip install --upgrade paddleocr

from paddleocr import PaddleOCR

ocr = PaddleOCR()
ocr.download()