# -*- coding: utf-8 -*-
"""pdf2Img.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wcVmi10M8Jt_5UXoTpJ59tRW0q191OzU
"""

!apt-get install -y poppler-utils
!pip install pdf2image

from pdf2image import convert_from_path
import os
import pandas as pd

#docTR
! pip install python-doctr
# for TensorFlow
! pip install "python-doctr[tf]"
# for PyTorch
! pip install "python-doctr[torch]"

from doctr.io import DocumentFile
from doctr.models import ocr_predictor
model = ocr_predictor(det_arch = 'db_resnet50',
                      reco_arch = 'crnn_vgg16_bn',
                      pretrained = True
                     )

def convert_pdfs_and_save_text(input_folder, output_folder):

    # Get all PDF files in the input folder
    pdf_files = [file for file in os.listdir(input_folder) if file.endswith(".pdf")]


    # Process each PDF
    for pdf_file in pdf_files:
        pdf_base_name = os.path.splitext(pdf_file)[0]
        pdf_file_path = os.path.join(input_folder, pdf_file)
        print("pdf_file_path is",pdf_file_path)
        # Convert PDF to an image
        images = convert_from_path(pdf_file)

        image_path = f"{output_folder}/{pdf_base_name}.png"
        images[0].save(image_path)
        img_DOCTR = DocumentFile.from_images("crop.jpeg")

        # use pre-trained model
        result = model(img_DOCTR)

        # export the result as a nested dict
        extract_info_DOCTR = result.export()
        result_DOCTR=extract_info_DOCTR['pages']
        for i in result_DOCTR:

          for j in i['blocks']:
            for k in j['lines']:
              for l in k['words']:
                print(l['value'])


# Example usage:
input_folder_path = "/content"  # Change this to the path of your input folder
output_folder_path = "/content/output_images"

# Create the output folder if it doesn't exist
if not os.path.exists(output_folder_path):
    os.makedirs(output_folder_path)

# Convert PDFs to images and extract text
convert_pdfs_and_save_text(input_folder_path, output_folder_path)